GET http://localhost:8080/greet
###
GET http://localhost:8080/greet/Tom
###
GET http://localhost:8080/admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJkYXRlIjoiMjAyMi0wNy0yMVQxNTozODo1Mi43OTUxMDY2MDIiLCJzdWIiOiJkZW1vIiwicm9sZSI6InVzZXIiLCJtZXNzYWdlIjoic29tZSBvdGhlciBtZXNzYWdlIiwiZXhwIjoxNjU4NDE2MTMyLCJpYXQiOjE2NTgzOTgxMzJ9.73ajNOVwD1oEolTv8IWGmP6cnxnARyuHmoW2XCrs_CWpX3Shrs-4kEUP1RnNgdI2A7JhQLaKPJV-uZ-TCTgqdQ

###
GET http://localhost:8080/manager
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJkYXRlIjoiMjAyMi0wNy0yMVQxNTozODo1Mi43OTUxMDY2MDIiLCJzdWIiOiJkZW1vIiwicm9sZSI6InVzZXIiLCJtZXNzYWdlIjoic29tZSBvdGhlciBtZXNzYWdlIiwiZXhwIjoxNjU4NDE2MTMyLCJpYXQiOjE2NTgzOTgxMzJ9.73ajNOVwD1oEolTv8IWGmP6cnxnARyuHmoW2XCrs_CWpX3Shrs-4kEUP1RnNgdI2A7JhQLaKPJV-uZ-TCTgqdQ

###
POST http://localhost:8080/authenticate
content-type: application/json

{
    "username": "demo",
    "password": "demo@123"
}
###
