GET http://3.91.240.112:8080/api/v1/movies

###

GET http://3.91.240.112:8080/api/v1/movies/2

###

GET http://3.91.240.112:8080/api/v1/movies/22

###

POST http://3.91.240.112:8080/api/v1/movies
content-type: application/json

{
  "title": "Shaktiman",
  "director": "Mukesh",
  "ratings": 4.7
}

###

PUT http://3.91.240.112:8080/api/v1/movies/6
content-type: application/json

{
  "title": "Rajnikant",
  "director": "Rajni",
  "ratings": 4.8
}

###

DELETE http://3.91.240.112:8080/api/v1/movies/5


