GET http://54.89.184.135:8080/api/v1/movies
###
GET http://54.89.184.135:8080/api/v1/movies/2
###
POST http://54.89.184.135:8080/api/v1/movies
content-type: application/json

{
  "title": "Monkey Power",
  "director": "Sonkey",
  "ratings": 3.6
}
###
PUT http://54.89.184.135:8080/api/v1/movies
###
DELETE http://54.89.184.135:8080/api/v1/movies/2
###

